version: "3"
services:
    php:
        build: .
        volumes:
            - "./current:/code"
            - "./nginx/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
            - "./phpsocket:/var/run"
    web:
        image: "nginx"
        ports:
            - "8080:80"
        volumes:
            - "./current:/code"
            - "./nginx/conf/admin.conf:/etc/nginx/conf.d/default.conf"
            - "./phpsocket:/var/run"
        links:
            - "php"